# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 13:16
# from __future__ import unicode_literals
#
from django.db import migrations, models
#
#
class Migration(migrations.Migration):
    pass
#
#     dependencies = [
#         ('wozdata', '0002_other_woz_objects'),
#     ]
#
#     operations = [
#         migrations.CreateModel(
#             name='NummeraanduidingGebruiksdoel',
#             fields=[
#                 ('id', models.AutoField(primary_key=True, serialize=False)),
#                 ('nummeraanduiding', models.CharField(db_index=True, max_length=14)),
#                 ('code', models.CharField(max_length=4)),
#                 ('omschrijving', models.CharField(max_length=50)),
#             ],
#             options={
#                 'ordering': ('nummeraanduiding',),
#             },
#         ),
#     ]
#
