# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 08:06
# from __future__ import unicode_literals
#
from django.db import migrations, models
#
#
class Migration(migrations.Migration):
    pass
#
#     dependencies = [
#         ('wozdata', '0003_nummeraanduidinggebruiksdoel'),
#     ]
#
#     operations = [
#         migrations.AlterField(
#             model_name='nummeraanduidinggebruiksdoel',
#             name='nummeraanduiding',
#             field=models.CharField(db_index=True, max_length=16),
#         ),
#     ]
#
