stages:
  - build
  - push
  - deploy

variables:
  DEPLOYMENT_WEB_IMAGE: ${CI_REGISTRY_IMAGE}-web
  DEPLOYMENT_DB_IMAGE: ${CI_REGISTRY_IMAGE}-db
  DOCKER_DRIVER: overlay

build:
  stage: build
  script:
  - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
  - docker build --pull -t ${CI_REGISTRY_IMAGE}-web:${CI_COMMIT_SHA:0:8} ./web
  - docker build --pull -t ${CI_REGISTRY_IMAGE}-db:${CI_COMMIT_SHA:0:8} ./database
  - docker push ${CI_REGISTRY_IMAGE}-web:${CI_COMMIT_SHA:0:8}
  - docker push ${CI_REGISTRY_IMAGE}-db:${CI_COMMIT_SHA:0:8}

push:
  stage: push
  script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker pull ${CI_REGISTRY_IMAGE}-web:${CI_COMMIT_SHA:0:8}
    - docker tag ${CI_REGISTRY_IMAGE}-web:${CI_COMMIT_SHA:0:8} ${DEPLOYMENT_WEB_IMAGE}:acceptance
    - docker pull ${CI_REGISTRY_IMAGE}-db:${CI_COMMIT_SHA:0:8}
    - docker tag ${CI_REGISTRY_IMAGE}-db:${CI_COMMIT_SHA:0:8} ${DEPLOYMENT_DB_IMAGE}:acceptance
    - docker push ${DEPLOYMENT_WEB_IMAGE}:acceptance
    - docker push ${DEPLOYMENT_DB_IMAGE}:acceptance
  only:
    - master

deploy_acceptance:
  stage: deploy
  environment:
    name: acceptance
    url: https://acc.api.secure.amsterdam.nl/woz

  image: cdrx/rancher-gitlab-deploy:latest
  script:
    - upgrade --stack WozApiStack --service web --new-image ${DEPLOYMENT_WEB_IMAGE}:acceptance
  only:
    - master

deploy_database_acceptance:
  stage: deploy
  when: manual
  environment:
    name: acceptance
    url: https://acc.api.secure.amsterdam.nl/woz

  image: cdrx/rancher-gitlab-deploy:latest
  script:
    - upgrade --stack WozApiStack --service database --new-image ${DEPLOYMENT_DB_IMAGE}:acceptance
  only:
    - master

deploy_prod:
  stage: deploy
  when: manual
  environment:
    name: production
    url: https://api.amsterdam.nl/woz

  image: cdrx/rancher-gitlab-deploy:latest
  script:
    - upgrade --stack WozApiStack --service web --new-image ${DEPLOYMENT_WEB_IMAGE}
  only:
    - master

deploy_database_prod:
  stage: deploy
  when: manual
  environment:
    name: production
    url: https://api.amsterdam.nl/woz

  image: cdrx/rancher-gitlab-deploy:latest
  script:
    - upgrade --stack WozApiStack --service database --new-image ${DEPLOYMENT_DB_IMAGE}
  only:
    - master
