stages:
  - build
#  - test
  - push
  - deploy

variables:
  DEPLOYMENT_IMAGE: ${CI_REGISTRY_IMAGE}

build:
  stage: build
  script:
  - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
  - docker build --pull -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA:0:8} ./web
  - docker push ${CI_REGISTRY_IMAGE}_web:${CI_COMMIT_SHA:0:8}
  - docker build --pull -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA:0:8} ./database
  - docker push ${CI_REGISTRY_IMAGE}_database:${CI_COMMIT_SHA:0:8}

#  We run tests in Datapunt jenkins pipeline
#test:
#  stage: test
#  script:
#    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
#    - docker run --rm ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA:0:8} ./manage.py test

push:
  stage: push
  script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker pull ${CI_REGISTRY_IMAGE}_web:${CI_COMMIT_SHA:0:8}
    - docker tag ${CI_REGISTRY_IMAGE}_web:${CI_COMMIT_SHA:0:8} ${DEPLOYMENT_IMAGE}_web:acceptance
    - docker push ${DEPLOYMENT_IMAGE}_web:acceptance
    - docker pull ${CI_REGISTRY_IMAGE}_database:${CI_COMMIT_SHA:0:8}
    - docker tag ${CI_REGISTRY_IMAGE}_database:${CI_COMMIT_SHA:0:8} ${DEPLOYMENT_IMAGE}_database:acceptance
    - docker push ${DEPLOYMENT_IMAGE}_database:acceptance
  only:
    - master

deploy_acceptance:
  stage: deploy
  environment:
    name: acceptance
    url: https://api.acc.amsterdam.nl/woz

  image: cdrx/rancher-gitlab-deploy:latest
  script:
    - upgrade --stack WozApiStack --service WozApi --new-image ${DEPLOYMENT_IMAGE}:acceptance
  only:
    - master

deploy_prod:
  stage: deploy
  when: manual
  environment:
    name: production
    url: https://api.amsterdam.nl/woz

  image: cdrx/rancher-gitlab-deploy:latest
  script:
    - upgrade --stack WozApiStack --service WozApi --new-image ${CONTAINER_IMAGE}
  only:
    - master
