version: '2'
services:
  database:
    image: repo.secure.amsterdam.nl/datapunt/woz/database:acceptance
    mem_reservation: 2048m
    privileged: true
    labels:
      io.rancher.scheduler.affinity:host_label_soft: highmem=true
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_DB: woz
      POSTGRES_USER: woz

  web:
    image: repo.secure.amsterdam.nl/datapunt/woz/web:acceptance
    links:
      - database:database
    environment:
      SECRET_KEY: insecure
      DATABASE_NAME: woz
      DATABASE_PASSWORD: insecure
      UWSGI_HTTP: ":8000"
      UWSGI_MODULE: "woz.wsgi:application"
      UWSGI_MASTER: 1
      UWSGI_STATIC_MAP: "/static=/static"
      UWSGI_DIE_ON_TERM: 1
    command: >
      bash -c "/app/.jenkins/docker-wait.sh && /app/docker-migrate.sh && uwsgi"
