version: "3.0"
services:
  database:
    image: amsterdam/postgres11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_DB: woz
      POSTGRES_USER: woz
    volumes:
      - "~/.ssh/datapunt.key:/root/.ssh/datapunt.key"

  web:
    build: ./web
    volumes:
      - $PWD/web/fixtures/:/app/data/fixtures
    ports:
      - "8119:8000"
    links:
      - database:database
    environment:
      BAG_OBJECTSTORE_PASSWORD:
      SECRET_KEY: insecure
      DATABASE_NAME: woz
      DATABASE_PASSWORD: insecure
      UWSGI_HTTP: ":8000"
      UWSGI_MODULE: "woz.wsgi:application"
      UWSGI_MASTER: 1
      UWSGI_STATIC_MAP: "/static=/static"
      UWSGI_DIE_ON_TERM: 1
    command: >
      bash -c "/app/.jenkins/docker-wait.sh && /app/docker-migrate.sh && uwsgi"
