version: "3.0"
services:
  database:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    ports:
      - "5459:5432"
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_DB: woz
      POSTGRES_USER: woz

  web:
    build: ./web
    ports:
      - "8119:8000"
    links:
      - database:database
    environment:
      SECRET_KEY: insecure
      DATABASE_NAME: woz
      DATABASE_PASSWORD: insecure
      OBJECTSTORE_PASSWORD:
      UWSGI_HTTP: ":8000"
      UWSGI_MODULE: "woz.wsgi:application"
      UWSGI_MASTER: 1
      UWSGI_STATIC_MAP: "/static=/static"
      UWSGI_DIE_ON_TERM: 1
